services:
  front_serve:
    build:
      context: ./front_side
    ports:
      - "8080:8080"
    depends_on:
      - server_fastapi

  server_fastapi:
    build:
      context: ./server_fastapi
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - QDRANT_URL=http://qdrant:6333

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:latest 
    container_name: qdrant
    ports:
      - "6333:6333"          
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo-data:
  qdrant_data: